export const LANDING = '/movieserver'
export const LANDING_TV = '/movieserver/tv'
export const MOVIE='/movieserver/movie/:id'
export const ACTOR = '/movieserver/actor/:id'
export const SEARCH='/movieserver/search/:searchTerm'
export const TV_DETAILS='/movieserver/tv/details/:id'